### ISSUE TITLE
VS Code 下编译结束后每次都会打开一个 PDF 文件

### ISSUE THREAD

**Issue by Codle** [bdebye/thesisuestc#137]
环境：

- MacBook Air M1
- VS Code Insider
- Latex WorkShop

无论 VS Code 怎么设置预览模式，编译后都会自动弹出打开 PDF 文件。

移除 [latexmkrc](https://github.com/x-magus/ThesisUESTC/blob/49b119ad26b01a1112759f83ca4a449de99a9f8e/latexmkrc#L6) 文件中的该行代码问题解决。

```
$preview_mode = 1;
```

目前不清楚是不是 M1 版本的 VS Code 还有点问题。

**Comment by sikouhjw** [comment]
命令行编译呢？调用 latexmk 应该跟编辑器没什么关系才对。

**Comment by Codle** [comment]
> 命令行编译呢？调用 latexmk 应该跟编辑器没什么关系才对。

也是如此，或者我个人感觉是一些设计逻辑上的原因。手动使用命令行编译的人一般写了很多内容才会去编译，此时弹出一个 PDF 作为预览很合理。而在 VS Code 中，一般我个人习惯写几个字就按下 Ctrl+S 保存并编译，此时如果一直弹出 PDF 就很烦。

**Comment by muzimuzhi** [comment]
> 而在 VS Code 中，一般我个人习惯写几个字就按下 Ctrl+S 保存并编译，此时如果一直弹出 PDF 就很烦。

频繁编译（例如 on Save） + 不自动弹出 PDF，是这样的需求吗？这样编译就只能用来检验有没有引入新 error，和看 log 分析结果了。

**Comment by Codle** [comment]
> 频繁编译（例如 on Save） + 不自动弹出 PDF，是这样的需求吗？这样编译就只能用来检验有没有引入新 error，和看 log 分析结果了。

我只是想来确认下其他环境（例如 Windows ）是否也是如此，我目前的解决方法是在 latexmkrc 里面移除 preview。这个个人感觉不应该作为一个需求来提出，可以在 README 或者相关文档处提一下即可，VS Code 里面的预览本身可以动态更新 PDF内容，不需要在编译链里面添加预览。

**Comment by x-magus** [comment]
latexmk设置是编译完成后自动打开pdf预览的，不同编辑环境可能会覆写某些设置。

**Comment by zepinglee** [comment]
`$preview_mode = 1;` 更适合放在个人的配置（`~/.latexmkrc`），不适合放在项目里。因为每个人可能有不同的编译习惯。

**Comment by PhiFever** [comment]
> > 命令行编译呢？调用 latexmk 应该跟编辑器没什么关系才对。
> 
> 也是如此，或者我个人感觉是一些设计逻辑上的原因。手动使用命令行编译的人一般写了很多内容才会去编译，此时弹出一个 PDF 作为预览很合理。而在 VS Code 中，一般我个人习惯写几个字就按下 Ctrl+S 保存并编译，此时如果一直弹出 PDF 就很烦。

https://www.cnblogs.com/lzhu/p/11189586.html 可以参考此文设置VSCODE使其在保存时不再自动编译
