### ISSUE TITLE
子图\subfloat报错Undefined control sequence

### ISSUE THREAD

**Issue by wycong0416** [bdebye/thesisuestc#204]
直接用原始的模板编译不过，求大佬解答一下，谢谢！
![f95a5978728e3bd0e4141cc631e513f](https://user-images.githubusercontent.com/37645231/179255630-91369964-e928-4939-8244-616c7e9834ea.png)

**Comment by bdebye** [comment]
一般这是由于texlive版本过旧造成的。

**Comment by wycong0416** [comment]
texlive升级到2022已解决该问题，谢谢！
