### ISSUE TITLE
生僻字怎么添加？

### ISSUE THREAD

**Issue by zyb296** [bdebye/thesisuestc#209]
生僻字怎么解决呢？pdf中无法显示，暂时查到了用SimSun，但是字体格式不一样

**Comment by sikouhjw** [comment]
1. 查阅已有 issue：https://github.com/bdebye/thesisuestc/issues/142
2. 详细解释什么叫『字体格式不一样』

**Comment by zyb296** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/40428932/223636664-6b2424d0-91bf-4a72-916a-96650ba4fc75.png">

**Comment by sikouhjw** [comment]
详细说明编译环境是什么，你用的是 Overleaf？

**Comment by zyb296** [comment]
> 对的

**Comment by zyb296** [comment]
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/40428932/223638246-f5fbf083-404f-423d-839d-1ab8af890292.png">

**Comment by sikouhjw** [comment]
`texdoc xeCJK`
```tex
\documentclass{ctexart}
\begin{document}
{
  \CJKfontspec{SimSun}[AutoFakeBold=true]\bfseries
  王垚
}
\end{document}
```

**Comment by zyb296** [comment]
> 
这个方法在正文中可以显示，但是指导老师这一块还是不行

**Comment by sikouhjw** [comment]
> > 
> 
> 这个方法在正文中可以显示，但是指导老师这一块还是不行

请给出你的依据，我这里没有任何问题。建议提供删减涉及隐私文本后的 Overleaf 分享链接。
![图片](https://user-images.githubusercontent.com/49770925/223641134-185ff12a-4060-48e9-97d7-5f0ea49ff6a0.png)

**Comment by zyb296** [comment]
> ```
> \CJKfontspec{SimSun}[AutoFakeBold=true]\bfseries
> ```

<img width="1852" alt="image" src="https://user-images.githubusercontent.com/40428932/223646157-2331fad2-1571-4e06-8288-9608e6cd7f33.png">
可以啦，已解决，感谢
