### ISSUE TITLE
公式字体似乎不太对

### ISSUE THREAD

**Issue by WEIFZH** [bdebye/thesisuestc#211]
例如： 

![image](https://user-images.githubusercontent.com/38351273/224470121-02b7597f-200a-408e-a1a6-e1c68cc991b8.png)

中的粗体z ($\mathbf{z}$) 与常见的粗体z，如
![image](https://user-images.githubusercontent.com/38351273/224470218-2802fda5-ceee-4ca5-870e-5b3e35caf79f.png)
不一样，请问是什么原因呢?有什么方法修改吗？

**Comment by note286** [comment]
你期望是什么样子，可以给个图。

**Comment by WEIFZH** [comment]
> 你期望是什么样子，可以给个图。
就是第二张图的样子，\mathbf{z} 在 github上编译出来也是这样 $\mathbf{z}$

**Comment by note286** [comment]
```latex
\documentclass[master]{thesis-uestc}
\begin{document}
$z$
$\mathbf{z}$
$\text{z}$
$\text{\textbf{z}}$

\textit{z}
\textbf{\textit{z}}
z
\textbf{z}
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/224472245-a26da81c-feff-4939-9a3b-1492b2696eb3.png)



`thesis-uestc.cls`用的是`mathspec`，因此数学字体也是Times New Roman，与正文一致。通过我给出的上面例子你应该就明白怎么回事了。

我更建议使用`unicode-math`，而不是`mathspec`。

**Comment by sikouhjw** [comment]
字体问题聊了很多次了，自己翻 issue，想改就自己改，改不动就接受模板

**Comment by WEIFZH** [comment]
如果要换的话，是不是可以参考 #148 中的方案？

**Comment by sikouhjw** [comment]
> 如果要换的话，是不是可以参考 #148 中的方案？

是的，记得先备份一下再改。因为 #148 的回答是之前的，现在能不能用我也不确定。
