### ISSUE TITLE
参考文献编号问题

### ISSUE THREAD

**Issue by WEIFZH** [bdebye/thesisuestc#213]
突然发现的现象,不知道算不算bug.

在使用图题索引 "\thesisfigurelist"之后,如果图 题引用了参考文献,优于它在正文的前面,所以编号会从它这个开始算...

导致正文第一个参考文献的编号不是"1". 我的解决方法是选择不用图题表题索引

**Comment by note286** [comment]
当然你可以选择给`\caption`加上可选参数来规避这个现象。

我这里提供一个命令，可以避免你所述的现象。

```latex
\documentclass{ctexart}
\usepackage{gbt7714}
\makeatletter
\NewDocumentCommand{\noauxwrite}{m}{\if@filesw\@fileswfalse #1\@fileswtrue\else #1\fi}
\makeatother
\begin{document}
\listoffigures
\cite{angenendt}\cite{augustine}
\begin{figure}[h]
\caption{title\noauxwrite{\cite{augustine}}}
\end{figure}
\bibliographystyle{gbt7714-numerical}
\bibliography{biblatex-examples}
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/224859600-ccd2203c-3f7f-4bc0-a68d-8733fd592056.png)

**Comment by note286** [comment]
你也可以选择使用`notoccite`包。

```latex
\documentclass{ctexart}
\usepackage{gbt7714}
\usepackage{notoccite}
\begin{document}
\listoffigures
\cite{angenendt}\cite{augustine}
\begin{figure}[h]
\caption{title\cite{augustine}}
\end{figure}
\bibliographystyle{gbt7714-numerical}
\bibliography{biblatex-examples}
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/224860420-74aa7f5f-3f69-46e5-bffe-b2d03043cc27.png)

**Comment by WEIFZH** [comment]
谢谢

> 你也可以选择使用`notoccite`包。
> 
> ```
> \documentclass{ctexart}
> \usepackage{gbt7714}
> \usepackage{notoccite}
> \begin{document}
> \listoffigures
> \cite{angenendt}\cite{augustine}
> \begin{figure}[h]
> \caption{title\cite{augustine}}
> \end{figure}
> \bibliographystyle{gbt7714-numerical}
> \bibliography{biblatex-examples}
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/16207292/224860420-74aa7f5f-3f69-46e5-bffe-b2d03043cc27.png)

谢谢！
