### ISSUE TITLE
Listing all authors in 'Thesis accomplishment' section.

### ISSUE THREAD

**Issue by Eldad27** [bdebye/thesisuestc#216]
According to the current format, The original bibliography lists authors up to the third author followed by et al. The accomplishment section follows this format and lists only 3 authors before adding et al. for other authors beyond 3. However, the requirement is to list all authors in the 'Research Results Obtained During the Study for Doctoral Degree' section. How is this accomplished? How do I fix this? Please help.

**Comment by note286** [comment]
I don't think it would be troublesome for most students to manually list their results.
