### ISSUE TITLE
macOS下编译后无法顺利通过格式审查

### ISSUE THREAD

**Issue by xulu199705** [bdebye/thesisuestc#219]
macOS下编译后无法通过学校指定的格式审查，格式审查系统会提示“未检测到正文”的warning，但是会显示“格式合格”。
~~~
$ tex --version
TeX 3.141592653 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 D.E. Knuth.
...(略)
~~~

目前我自己的解决方案是将项目在Windows下进行编译一次再提交，可以顺利通过格式审查。

**Comment by note286** [comment]
可能是字体的问题？我没看默认macOS下使用什么字体，你可以安装中易字体试试。

**Comment by xulu199705** [comment]
是的，macOS下的宋体确实与Windows的不同；大概是宋体的名称不一样导致这个问题出现。

**Comment by note286** [comment]
你可以把

https://github.com/bdebye/thesisuestc/blob/2320c99d64b0ca6f2f47e69183a66e6dfb67eac9/thesis-uestc.cls#L50-L71

改为

```latex
\setCJKmainfont[AutoFakeBold=true]{SimSun}
\newCJKfontfamily{\heiti}{SimHei}
\newfontfamily{\heiti@letter}{SimHei}
\setallmainfonts{Times New Roman}
```

然后给macOS安装以上三个字体即可。

**Comment by xulu199705** [comment]
明白，谢谢。
