### ISSUE TITLE
附录插入公式

### ISSUE THREAD

**Issue by zyb296** [bdebye/thesisuestc#223]
请问一下怎么在附录插入公式呢？需要在*.cls文件中导入listings包吗？参考：https://www.jianshu.com/p/fb1c1c6f2d02

**Comment by sikouhjw** [comment]
# 如何插入公式？
```tex
\[ test \]
```

# 如何插入代码块？

在导言区加载 `listings` or `minted` 宏包，阅读其手册再使用。
