### ISSUE TITLE
图题和表题字号

### ISSUE THREAD

**Issue by Chen-Suyi** [bdebye/thesisuestc#231]
非常感谢学长提供的模板。

我在Overleaf上编译时图题和标题的字号看起来偏小，似乎是小五。

请问图题和表题的字号定义在何处？

硕士论文要求图题和标题的字号大小为五号。但是实际在Overleaf上编译后看起来比五号小了一些。希望可以找到定义字号的地方方便修改。

**Comment by Chen-Suyi** [comment]
非常感谢解答

看来原因出现在bp和pt单位的微小差距上，bp实际上比pt略小。

参考[中科大论文模板的issue](https://github.com/ustctug/ustcthesis/issues/4)
Word中定义磅数用的是bp作为单位，而该LaTex模板中用的磅数单位是pt，是否将其修改过来会更好呢？

**Comment by Chen-Suyi** [comment]
是不是理论上把所有pt定义的地方替换成bp就能解决了？

有什么需要注意的地方吗？

**Comment by sikouhjw** [comment]
> 是不是理论上把所有pt定义的地方替换成bp就能解决了？
> 
> 有什么需要注意的地方吗？

不是，模板的设置没有考虑到 bp 和 pt 的差异，因此直接转换是不对的。甚至于 `12pt` 本身就是错的，应当使用 `zihao={-4}` 即 `12bp`。

如果格式审查不是非常严格，建议算了。如果审出来这些细节，需要将模板中的大多数字号改了。

**Comment by Chen-Suyi** [comment]
我算了一下，其实bp和pt对于常用字号来说误差非常小，理论上肉眼看不出来才对。

后来发现应该是latex编译对文字和图片的压缩方法不同造成的。

在小于100%的缩放比例下，图中文字是按图片来处理的，图题文字是按字符处理的。字符缩放到一定程度时会将笔画细化，但是图中的文字却不会这样。导致在小百分比缩放下图中文字看起来比图题文字稍大。

如果将编译结果缩放得足够大，是看不出来差别的，打印的时候应该回事相同大小。所以不用纠结了。

**Comment by sikouhjw** [comment]
> 后来发现应该是latex编译对文字和图片的压缩方法不同造成的。

如何确定是 latex 的问题而不是图片的问题？例如图片为位图，位图的文字不会随着缩放比例而“变化”。

**Comment by Chen-Suyi** [comment]
用visio或者figma画并导出为pdf是可以控制图中文字大小的

然后再latex导入pdf的时候，不用类似width=\linewidth之类的命令改变图片大小的话，图中文字的大小就会是设定的大小。

能看到图中文字和图题文字的面积其实是一样的，但是在缩小显示的时候，图题文字的笔画明显会更细，看起来就比图中文字小。

**Comment by sikouhjw** [comment]
说的通俗一点，控制变量

**Comment by Chen-Suyi** [comment]
缩小显示：
<img width="328" alt="image" src="https://github.com/bdebye/thesisuestc/assets/141543096/eef89baf-ba28-4b1f-be91-62809eb04465">

放大显示：
<img width="488" alt="image" src="https://github.com/bdebye/thesisuestc/assets/141543096/1dc17aee-5f78-419e-b605-75e92f2f4fbb">


不同缩放效果下，图中文字看起来就是简单的缩放，而图题文字感觉直接换了个字体（对比“视角”两个字笔画粗细的区别，这里用的都是fzsong.ttf提供的字体）

所以仅仅只是latex编译显示效果的差异罢了，不用太纠结（暂时不知道会不会影响打印的效果）

**Comment by note286** [comment]
当你在提问的时候，默认不会完全相信你的描述。从五天前开始的沟通效率一直就很低，一开始就应该给出代码和对应的PDF。

**Comment by sikouhjw** [comment]
0. 将文字转曲后插入文档中以此对比
```tex
\documentclass{ctexart}
\usepackage{graphicx}
\begin{document}
\begin{figure}
  \centering
  \includegraphics[width=\ccwd,angle=-90]{test1.pdf}

  测试
  \caption{测试}
\end{figure}
\end{document}
```
1. 在 SumatraPDF 中，放大效果为
   ![图片](https://github.com/bdebye/thesisuestc/assets/49770925/1a7ea661-946e-4ed8-b560-ee38ed554dc8)
   缩小效果为
   ![图片](https://github.com/bdebye/thesisuestc/assets/49770925/97b7d869-9fc2-4ecc-9e89-0bb94b5fb0da)
2. 在 Adobe Acrobat 中，放大效果为
   ![图片](https://github.com/bdebye/thesisuestc/assets/49770925/a4d04ff0-f523-436e-81c3-dbe6e096cc55)
   缩小效果为
   ![图片](https://github.com/bdebye/thesisuestc/assets/49770925/c342a0d7-ee40-4bb4-8584-4d21176c6db7)
3. 由此可见，字符显示效果是由是否转曲以及 pdf 阅读器的渲染决定的，跟 latex 无关，你用 word 去实现也是一样的。
