### ISSUE TITLE
新版的引用文献要求英文作者名字缩写不加"."，怎么修改bst文件呢？

### ISSUE THREAD

**Issue by Allogeness** [bdebye/thesisuestc#235]
作者姓在前、名在后，英文姓全拼、首字母大写，英文名大写缩写且不加点，例如“Harrington R F”（Roger F. Harrington），“Li M”（Li Moumou）；

**Comment by bdebye** [comment]
最新的commit已经解决了这个问题，现在外文名是按照格式的要求显示了。
